version: "3.8"

services:
  # Node.js application service
  microservice:
    build: .
    ports:
      - "8001:8001"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=localhost
      - DB_PORT=5430
      - DB_NAME=orders
    depends_on:
      - db

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
