version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  migrate:
    build:
      context: .
      target: builder
    depends_on:
      - db
    command: sh -c "pnpm generate && pnpm migrate"
    # command: sh -c "sleep 300"

  microservice:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - migrate
