version: "3.8"

services:
  # Node.js application service
  microservice:
    build: .
    ports:
      - "8004:8004"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=db
      - DB_PORT=5427
      - DB_NAME=wishlist
    depends_on:
      - db

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5427:5432"
